services:
  patient-service-db:
    image: postgres:latest
    container_name: patient-service-db
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: patient_service_db
    ports:
      - "5000:5432"
    volumes:
      - C:/Users/OLIVER TECH/Desktop/docker/db_volumes/patient-management:/var/lib/postgresql/data
    networks:
      - internal

  patient-service:
    build: .
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient-service-db:5432/patient_service_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    ports:
      - "4000:4000"
    networks:
      - internal

networks:
  internal:
    external: true


